#include "helper.h"
#include "visual.h"
#include <stdio.h>


void output_uvp(const char *szProblem,
		 int    timeStepNumber,
		 double xlength,
                 double ylength,
                 int    imax,
                 int    jmax,
		 double dx,
		 double dy,
                 double **U,
                 double **V,
                 double **P,
		int il,int ir,int jb,int jt,int myrank
) {

  int i,j;
  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.%i.vtk", szProblem,myrank, timeStepNumber);
  fp = fopen( szFileName, "w");
  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  write_vtkHeader( fp, il,ir,jb,jt, dx, dy);
  write_vtkPointCoordinates(fp, il,ir,jb,jt, dx, dy);

  fprintf(fp,"POINT_DATA %i \n", (ir-il+2)*(jt-jb+2) );

  fprintf(fp,"\n");
  fprintf(fp, "VECTORS velocity float\n");
  for(j = jb-1; j < jt+1; j++) {
    for(i = il-1; i < ir+1; i++) {
      fprintf(fp, "%f %f 0\n", (U[i][j] + U[i][j+1]) * 0.5, (V[i][j] + V[i+1][j]) * 0.5 );
    }
  }

  fprintf(fp,"\n");
  fprintf(fp,"CELL_DATA %i \n", ((ir-il+1)*(jt-jb+1)) );
  fprintf(fp, "SCALARS pressure float 1 \n");
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(j = jb; j < jt+1; j++) {
    for(i = il; i < ir+1; i++) {
      fprintf(fp, "%f\n", P[i][j] );
    }
  }

  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}


void write_vtkHeader( FILE *fp, int il,int ir,int jb,int jt,
                      double dx, double dy) {
  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by CFD-lab course output (written by Shulin, Teng and Andrea) \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i 1 \n", ir-il+2, jt-jb+2);
  fprintf(fp,"POINTS %i float\n", (ir-il+2)*(jt-jb+2) );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int il, int ir,int jb,int jt,
                      double dx, double dy) {

  int i = 0;
  int j = 0;

  for(j = jb-1; j<=jt; j++) {
    for(i = il-1; i<=ir; i++) {
      fprintf(fp, "%f %f 0\n", i*dx, j*dy);
    }
  }
}


